spring.application.name=employee-service

# server
server.port = 8080

# default servlet mapping
server.servlet.context-path=/api/v1

# jwt
jwt.secret = uegiyg9yiywg9u3qeuqv9yrwf0bih93qehivcddiysgojq33uigiywbo237ygibds08yf4ihbwiuhy08yefwi8

# oauth

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}

spring.profiles.active=dev