spring.application.name=employee-service

# server
server.port = 8081

# default servlet mapping
server.servlet.context-path=/api/v1

# jwt
jwt.secret = uegiyg9yiywg9u3qeuqv9yrwf0bih93qehivcddiysgojq33uigiywbo237ygibds08yf4ihbwiuhy08yefwi8

spring.profiles.active=dev